Course work1
andr777/CourseWwork1BookOfEmployees pull request #1
Opened 2022-09-07 00:58 UTC by andr777

Курсовое задание. Книга сотрудников

2022-09-07 17:25 UTC, OlgaLugacheva requested changes

2022-09-07 17:25 UTC, OlgaLugacheva commented on src/Employee.java
> +
будет здорово добавить toString, equals, hashCode

2022-09-07 17:25 UTC, OlgaLugacheva commented on src/Main.java
> +                        + "   зарплата: " + employees[i].getSalary() + "$");
здесь аналогично - по полям не нужно вызывать сеттеры. нужно просто переопределить toString

2022-09-07 17:25 UTC, OlgaLugacheva commented on src/Main.java
> +                + employees[employeesMin()].getName()
вот как раз тут потребуется переопределенный toString

2022-09-07 17:25 UTC, OlgaLugacheva commented on src/Employee.java
> +    int id;                 // номер
нужно добавить модификаторы доступа

2022-09-07 21:55 UTC, andr777 commented on src/Employee.java
> +
добавил toString, equals, hashCode

"будет здорово" или "необходимо для сдачи курсовой" ? а тож улучшать программу можно бесконечно, windows b ms office до сих пор улучшают и до сих пор не сделали последнюю на 100% готовую версию.

2022-09-07 21:56 UTC, andr777 commented on src/Main.java
> +                        + "   зарплата: " + employees[i].getSalary() + "$");
сделал, 
теперь toString выводит все поля и их данные

2022-09-07 21:57 UTC, andr777 commented on src/Main.java
> +                + employees[employeesMin()].getName()
тут не получится, тут по заданию надо выводить только Ф.И.О., а переопределённый toString уже выводит весь список полей, по вашему же пожеланию, см.комменты выше.
сделал toStringFullName, выводит только ФИО

2022-09-07 21:58 UTC, andr777 commented on src/Employee.java
> +    int id;                 // номер
сделал

2022-09-08 05:58 UTC, OlgaLugacheva commented on src/Employee.java
> +
toString здесь необходим, чтобы не выводить по полям. Есть общепринятые нормы , которыми стоит руководоствоваться.

2022-09-08 06:43 UTC, merged